### ISSUE TITLE
META: Missing Official Equipment

### ISSUE THREAD

**Issue by Algebro7** [WEKarnesky/solarisskunkwerks#12]
The following official equipment needs to be implemented in SSW:

## Ballistic
- [ ] Gauss Rifle (Prototype) (IS, Pg72 IO)
- [ ] Imp.AC/2 (Clan, Pg96 IO)
- [ ] Imp.AC/5 (Clan, Pg96 IO)
- [ ] Imp.AC/10 (Clan, Pg96 IO)
- [ ] Imp.AC/20 (Clan, Pg96 IO)
- [ ] Imp.Gauss Rifle (Clan, Pg96 IO)
- [ ] LB-02-X AC (Prototype) (Clan, Pg97 IO)
- [ ] LB-05-X AC (Prototype) (IS, Pg 72 IO)
- [ ] LB-10-X AC (Prototype) (Clan, Pg97 IO)
- [ ] LB-20-X AC (Prototype) (Clan, Pg97 IO)
- [ ] Ultra AC/2 (Prototype) (Clan, Pg98 IO)
- [ ] Ultra AC/5 (Prototype) (IS, Pg 104 IO)
- [ ] Ultra AC/10 (Prototype) (Clan, Pg98 IO)
- [ ] Ultra AC/20 (Prototype) (Clan, Pg98 IO)
## Energy
- [ ] Centurion Weapon System (IS, Pg85 IO)
- [ ] Enhanced PPC (Clan, Pg95 IO) 
- [ ] Improved PPC (Clan, Pg95 IO)
- [ ] ER Large Laser (Prototype) (IS, Pg103 IO)
- [ ] Medium Pulse Laser (Prototype) (IS, Pg103 IO)
- [ ] RISC Hyper Laser (IS, Pg93 IO)
- [ ] RISC Repeating TSEMP (IS, Pg94 IO)

**Comment by WEKarnesky** [comment]
Added tech bases and reference pages

**Comment by WEKarnesky** [comment]
Added missing Energy equipment.

**Comment by kevinn** [comment]
@Algebro7 LB-05-X AC (Prototype) (IS, Pg 72 IO) should be a LB-10-X AC.

BTW, in the ods document that i sent to @WEKarnesky (Insaniac99 right?) - Clan Prototype UACs and LBXs are already filled under the book from Klondike, CMIIW.

Haven't added any the Energy weapons yet tho.
